### ISSUE TITLE
Increase proxy timeout for testing environments

### ISSUE THREAD

**Issue by fetchandadd** [scce/dywa-ansible-role#53]
/FYI @snaujokat 
```
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
```

**Comment by fetchandadd** [comment]
@snaujokat Because of the new native schema of DyWA (where the reset endpoint responses fast enough) this is not an issue anymore, right?

**Comment by snaujokat** [comment]
@timtegeler With the amount of data we tested so far, /reset took at most 15 seconds. So yes, 60 seconds default timeout should be fine for now. We can reopen this issue if the need arises again.

**Comment by fetchandadd** [comment]
Great!
