### ISSUE TITLE
app.py: Wrong argument name

### ISSUE THREAD

**Issue by MazeChaZer** [scce/dywa-ansible-role#60]
https://github.com/scce/dywa-ansible-role/blob/b8aa550a92005b4a47161ce611129094fa886a2b/templates/app/app.py#L57
When the database password for the migration is set, the wrong argument name is used.

**Comment by fetchandadd** [comment]
@MazeChaZer Thanks for the bug report. 

Please can you review the referenced commit 82bc568 and close the issue if you don't have any comments?

**Comment by MazeChaZer** [comment]
Looks good :+1:
